language: node_js
os:
  - linux
  - osx
node_js:
  - "10"
  - "12"
  - "13"
# after_script:
  # Run `npm run coverage` locally to submit coverage data to coveralls.io.
  # Be sure to have a .coveralls.yml file with valid token.
branches:
  only:
  - dev
  - npm
  - v1-lts
  # After releasing, bump to next anticpated version.
  - v1-lts@1.7.11
