name: Mac build

on:
  push:
    branches:
      - dev
      - v1-lts
      # After releasing, bump to next anticpated version.
      - v1-lts@1.7.11
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 13.x
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm test
          npx nyc report --reporter=text-lcov > ./lcov.info

      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
